### ISSUE TITLE
Clarify support & type usage in documentation

### ISSUE THREAD

**Issue by CRBroughton** [Desdaemon/typed-htmx#3]
Hi there, I've been playing around with HTMX and your library, however I'm having a bit of trouble following the second method of installation:

'An alternative is to include a [triple-slash directive](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) wherever you need completions for htmx attributes'

As far as I can tell, this isn't true for TypeScript; I've attempted to add the reference directive to a single component I created, however, including this reference causes other parts of my application (in other files) to have type issues (I'm using Hono as a server).

I found a reference on the TypeScript repository explaining this same issue:

https://github.com/Microsoft/TypeScript/issues/19978

Here is my working repository and branch with the issue replicated - https://github.com/CRBroughton/htmx-contacts-app/tree/github-example-broken

Do you have any recommendations on how I can resolve the above? Either by modifying what I already have, or an alternative to the reference?

Thank you for the library, and your time :)

**Comment by Desdaemon** [comment]
For the repo you mentioned in particular, it might work if you add 'typed-htmx' in the types section of tsconfig.json next to 'bun-types'.

From what I could gather reading the TS issue, adding a triple-slash directive would actually clear out all entries in the types section and add only those present in the declaration files.

**Comment by CRBroughton** [comment]
HI there, thanks for the reply :)

I've added in the types to the tsconfig as suggested, but it's still falling over on the hono.tsx file. Seems to be something to do with the types `HtmlEscapedString | Promise<HtmlEscapedString>` from Hono, and the `string` type that is now expected.

![Screenshot from 2023-12-30 23-18-34](https://github.com/Desdaemon/typed-htmx/assets/71838537/2d60747f-5a94-43b8-a4fc-5c9fa7c49d5b)

I'll keep poking at it tomorrow and see if I can get it to work; So far the best I've found is type-casting with `as HtmlEscapedString | Promise<HtmlEscapedString>` on every bit of HTML.

Thanks again for the help.

**Comment by Desdaemon** [comment]
I've included an example with Hono for your reference, hopefully this works!

**Comment by Desdaemon** [comment]
If you have a reproduction repo I might be able to take a look at it soon

**Comment by bertez** [comment]
thanks for your reply, here it is:

https://github.com/bertez/node-hono-test

it happens with bun as well

**Comment by Desdaemon** [comment]
I fixed this but didn't publish the changes, it's on 0.2.1 now

**Comment by bertez** [comment]
thank you! it works
