### ISSUE TITLE
@types/ on npm

### ISSUE THREAD

**Issue by mrinc** [Desdaemon/typed-htmx#4]
Hey,  

I know it is possible, but what are your thoughts on using DT `@types/` instead of just typed-htmx?  

My logic here is most ts-config files will include `@types/` so instead of manually adding the typed-htmx to the tsconfig, we can just `npm i --save-dev @types/react-htmx` and it's working (simpler)  
Since this isn't v1 yet and changes will occur, it definitely makes it more difficult to push changes/updates to it - so maybe not now but later.

**Comment by Desdaemon** [comment]
If my understanding from recent issues is correct, this will only work if `react-htmx` itself is a module that you either import or add as ambient types in tsconfig.json. And even if such a module exists, it is likely to bring in its own Typescript definitions that will clash with ours. I'll revisit this if there is a clear demand for it.
